artifact_uri: ~/Desktop/0/eaaaa931f73840b5a2d333690a739eeb/artifacts
end_time: 1585168068724
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: eaaaa931f73840b5a2d333690a739eeb
run_uuid: eaaaa931f73840b5a2d333690a739eeb
source_name: ''
source_type: 4
source_version: ''
start_time: 1585168068701
status: 3
tags: []
user_id: amritbaveja
