artifact_uri: ~/Desktop:5001/0/92ec3bcd390d44ec9b39936647abe7de/artifacts
end_time: 1585168101378
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 92ec3bcd390d44ec9b39936647abe7de
run_uuid: 92ec3bcd390d44ec9b39936647abe7de
source_name: ''
source_type: 4
source_version: ''
start_time: 1585168101354
status: 3
tags: []
user_id: amritbaveja
